server:
  port: 8083

spring:
  data:
    mongodb:
      url: mongodb://localhost:27017
      database: microservicios

  application:
    name: CALIFICACION-SERVICE

  config:
    import: optional:configserver:http://localhost:8085
