server:
  port: 8085
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GabrielGomezGG/Spring-Boot-Udemy
          clone-on-start: false

