server:
  port: 8085
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/GabrielGomezGG/Spring-Boot-Udemy/tree/master/Microservicios/Proyecto01
          clone-on-start: false

